version: '3.8'
services:
  server:
    image: supply-chain-server-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: supply-chain-server-dev-c
    volumes:
      - ./server:/app
      - ./app/node_modules/
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
  client:
    image: supply-chain-client-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: supply-chain-client-dev-c
    volumes:
      - ./client:/app
      - ./app/node_modules/
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
