version: '3.8'
services:
  server:
    image: supply-chain-server-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: supply-chain-server-dev-c
    volumes:
      - ./server:/app
      - ./app/node_modules/
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - ACCESS_TOKEN_SECRET=9ce653b372acf228
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
    command: ["sh", "-c", "npm run prisma:migrate && npm run prisma:seed && npm run dev"]

  client:
    image: supply-chain-client-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: supply-chain-client-dev-c
    volumes:
      - ./client:/app
      - ./app/node_modules/
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_API=http://localhost:4000/
      - NEXT_PUBLIC_ACCESS_TOKEN_SECRET=9ce653b372acf228
    stdin_open: true
    tty: true

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres-data:
