version: '3.8'
services:
  server:
    image: supply-chain-server-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: supply-chain-server-dev-c
    volumes:
      - ./server:/app
      - ./app/node_modules/
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - ACCESS_TOKEN_SECRET=9ce653b372acf228
      - DATABASE_URL=postgresql://postgres:password@localhost:5432/postgres?schema=public
  client:
    image: supply-chain-client-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: supply-chain-client-dev-c
    volumes:
      - ./client:/app
      - ./app/node_modules/
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_API=http://localhost:4000/
      - NEXT_PUBLIC_ACCESS_TOKEN_SECRET=9ce653b372acf228
    stdin_open: true
    tty: true
