import { SupplyChainItemResponse } from "@/types";

export const items: SupplyChainItemResponse[] = [
  {
    id: 3,
    title: "Car Parts",
    description: "something about cars",
    price: 19289,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
  {
    id: 5,
    title: "Car Parts",
    description: "something about cars",
    price: 19289,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
  {
    id: 6,
    title: "Car Parts",
    description: "something about cars",
    price: 19289,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
  {
    id: 7,
    title: "Car Parts",
    description: "something about cars",
    price: 19289,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
  {
    id: 8,
    title: "Car Parts",
    description: "something about cars",
    price: 19289,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
  {
    id: 9,
    title: "Car Parts",
    description: "something about cars",
    price: 19289,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
  {
    id: 10,
    title: "Car Parts",
    description: "something about cars",
    price: 19289,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
  {
    id: 11,
    title: "Car Parts",
    description: "something about cars",
    price: 19289,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
  {
    id: 13,
    title: "Car Parts",
    description: "something about cars",
    price: 19289,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
  {
    id: 14,
    title: "Car Parts",
    description: "something about cars",
    price: 0,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
  {
    id: 15,
    title: "Car Parts",
    description: "",
    price: 0,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
  {
    id: 16,
    title: "Car Parts",
    description: "something about cars",
    price: 0,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
  {
    id: 17,
    title: "Car Parts",
    description: "something about cars",
    price: 0,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
  {
    id: 1,
    title: "Car and Bike Parts",
    description: "something about cars",
    price: 19289,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
  {
    id: 12,
    title: "Car Parts",
    description: "something about cars",
    price: 1234,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
  {
    id: 4,
    title: "Car Parts",
    description: "something about cars",
    price: 1234,
    creatorId: 1,
    creator: {
      id: 1,
      email: "alice@prisma.io",
      name: "Car and Bike Parts",
    },
  },
];
